### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by assignUser**
@mpadge What do you think? Is this README helpful enough?

### CODE REVIEW

**Comment by mpadge** [comment]
I'll have a bit of a go-over tomorrow. It's looking good

**Comment by mpadge** [comment]
@assignUser [The above commit](https://github.com/ropensci-review-tools/pkgcheck-action/pull/14/commits/15e875115c4c60e46207a816e06319198535a4ee) adds a simple script to auto-insert the inputs from the current `action.yaml`, to ensure the README will always be up to date with the action. Just `make` to update it. Note that it removes comments which are present in current README, yet not in the actual `yaml` - I'll commit a modified README in a moment, and you can decide whether you want to re-insert them or not.

**Comment by assignUser** [comment]
@mpadge Nice, reads well! 

Should we add the additonal comments to the actual yaml so they show up?

**Comment by mpadge** [comment]
> Should we add the additonal comments to the actual yaml so they show up?

That was my idea, yeah. Then you can run `make` to update the lot. Note that it tries to find `pkgcheck/inst/pkgcheck.yaml` via `file.path(here::here(), "..", "pkgcheck")`, and if it's not there, it reverts to installed version. Maybe make sure you've got both repos in one common directory to ensure README is always up to date with `pkgcheck.yaml`?

**Comment by assignUser** [comment]
I am going to set it up so that, if action.yaml was modified, a job will run that will use your script to update the readme. 
As the inputs are documented in {pkgcheck} we would need something similar there? I'll think about it...

**Comment by assignUser** [comment]
@mpadge I have integrated it into the action. It will skip the readme bit when it's a PR as the repo is in detached HEAD state and fixing that is more trouble than it is worth, so it now only happens on push or manual trigger (e.g. above) 

I had to create a dummy package so that {pak} would still install the dependencies for us to use but I opened an issue about that :D 

If you are happy with the contents of the readme I would say we are about ready to merge?

**Review by mpadge — APPROVED** [review]
@assignUser all good to go! More generally, I suggest we use tagged reviews for PRs - you assign me, and i assign you. I assigned myself here, and this is my official approval to merge. Great work - thanks!

**Pull request merged**
